version: '3.7'

services:
  web:
    build: ./microservices
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./microservices/:/usr/src/app/
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web